version: '3.4'
services:

  pinger:
    image: nefilim/pinger:1.0
    container_name: pinger
    restart: always
    command: -Xmx=64m -Xms=64m -Dconfig.file=/opt/docker/etc/application.conf -Dlogback.configurationFile=/opt/docker/etc/logback.xml
    volumes:
      - type: bind
        source: ./etc-pinger
        target: /opt/docker/etc

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    restart: always
    ports:
      - 9090:9090
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.retention=7d'
      - '--storage.tsdb.path=/prometheus'
    volumes:
      - type: bind
        source: ./prometheus.yml
        target: /etc/prometheus/prometheus.yml
      - type: bind
        source: ./prometheus-data
        target: /prometheus
    user: 0:0

